### ISSUE TITLE
Add mechanism to commit event changes

### ISSUE THREAD

**Issue by stveit** [Uninett/zino#52]
Issue of the inline comment 

`# TODO we need a mechanism to "commit" event changes, to trigger notifications to clients`

Cleaner to have it as an issue and not comment

**Comment by lunkwill42** [comment]
### Differences between Zino 1 and Zino 2 event states

#### Zino 1

Zino 1 operates mostly with a bunch of global key/value maps for everything.

Each event has its attributes stored in a dynamically allocated global map, e.g. like:

```tcl
set ::EventAttrs_138951(router) "ifi2-gw5"
set ::EventAttrs_138951(state) "waiting"
…
```

All attribute changes are controlled by calls to `setEventAttr`.  When the to above attributes are set, `setEventAttr` really sets these two values:


```tcl
set ::NewEventAttrs_138951(router) "ifi2-gw5"
set ::NewEventAttrs_138951(state) "waiting"
…
```

A later call to `commitEvent` will copy keys/values from `NewEventAttrs_138951` to `EventAttrs_138951`.

#### Zino 2

Zino 2 avoids global and dynamic variables.  All event attributes are stored in coherent event objects of the `Event` class, and the global state model keeps a list of all `Event` objects that are considered part of the running state.

At the current state of development, Zino 2 doesn't have a "commit" mechanism similar to that of Zino 1, but it seems now to need it.

**Comment by lunkwill42** [comment]
### Suggestions for Zino 2 implementations

The inclination of a Python programmer to change event state is to get the corresponding `Event` object from the state controller, and just set a variable, something like this, and be done with it:

```python
event = state.get_event(138951)
event.state = "waiting"
```

The drawbacks of this are:

1. The state change is immediate and will be persisted to disk the next time the scheduler runs the state dumper.
2. There is no signal to the state controller that anything changed.
3. There is no implicit log entry added to event `138951` to tell which username made a state change, since there is no username involved in any of this.


Number 2 could easily  be fixed by adding an observer pattern to the `Event` model, in which the state controller registers as an observer of all state changes.

Number 3 is not fixable by pure Python attribute setters.  The Zino 1 `setEventAttr` function takes an optional argument for a username.  If supplied, `setEventAttr` will ensure that a log entry is created.  However, this argument is only ever supplied by the server during the execution of the `SETSTATE` API command, so it isn't obvious that a generic solution is needed.  Zino 2 could get away with having a simple `Event.set_state(new_state, username)` method that both sets the state value and makes a log entry.

My suggested design is therefore to have a sort of `checkout` method in the event state controller (`zino.state.ZinoState.events`).  `checkout` would retrieve a **copy** of an existing `Event` object, which can be modified freely by the client code without affecting the running state.  A corresponding `commit` method would take an `Event` object as its input, replacing the corresponding `Event` object in the running state and then initiating the state dump scheduling and notification procedures just as Zino 1 does.

**Comment by hmpf** [comment]
Read, sounds good. This allows for easy logging of the other possible change as well: clear flapping. The copy can be dumped to disk as a backup and deleted from disk after the commit.

**Comment by lunkwill42** [comment]
> Read, sounds good. This allows for easy logging of the other possible change as well: clear flapping. 

> The copy can be dumped to disk as a backup and deleted from disk after the commit.

Not sure I want to engage with that, since it's not part of Zino 1.  

Anyhoo, we also need to trigger certain operations if the state changes to "closed":  That's when Zino 1 initiates dumping the closed event to a separate "backup" file per event, and schedules the event to be expunged entirely from the running state within a set time period.
